### ISSUE TITLE
No icon

### ISSUE THREAD

**Issue by dausruddin** [Gyran/rutorrent-pausewebui#2]
There are 2 invisible icon created at the menu bar. Is it possible to add icons for them?

**Comment by Gyran** [comment]
There should be icons, do you get any errors?

**Comment by dausruddin** [comment]
Sorry, I am no longer using rtorremt. Thanks.

**Comment by banjopotato** [comment]
I have this same problem: there are no icons in the top toolbar in rutorrent. There are blank spaces and, if I click on them, the pausewebui functionality is there, but the icons don't appear. I've checked permissions on the image files and all are 644. /var/www/html/rutorrent/plugins is 755. All belong to www-data.
![Screenshot 2023-01-01 at 10 24 36](https://user-images.githubusercontent.com/6973171/210167516-f09deead-44f5-474a-9547-374d02824726.png)
